// swift-ai-hub — Apache-2.0
// Snapshot fixtures for the @Generable / @Guide / @Tool / @Parameter macros
// using Point-Free's swift-macro-testing. Inline snapshots below are
// generated by re-running the suite with `record: .missing` and then locked
// in under `record: .never` so CI fails (rather than silently rewrites) on
// drift.
//
// Complements the existing SwiftSyntaxMacrosTestSupport-based tests; does
// not replace them. Matrix (per docs/09:36 audit-E):
//   1. @Generable struct (primitive properties)
//   2. @Generable struct with nested @Generable field ($ref / inline schema)
//   3. @Generable enum with associated values (regression for af92a6b)
//   4. @Guide(Regex) pattern propagation (regression for 91e2948)
//   5. @Tool simple (top-level with execute + nested Arguments)
//   6. @Tool + @Parameter (tool with @Parameter-marked Arguments field)
//
// Scope note: MacroTesting 0.6.x's `.macros(_:)` trait takes only
// `[String: Macro.Type]`; there's no public knob to declare the macro's
// `conformances:` list. Snapshots therefore capture the MemberMacro output
// (+ ExtensionMacro output that the macro itself emits via `extension`
// decl syntax, as @Tool does). @Generable's Codable/Generable extension
// conformances are validated behaviourally by GenerableCodableTests, not
// here.

#if os(macOS)
  import MacroTesting
  import Testing

  @testable import SwiftAIHubMacros

  @Suite(
    .macros(
      [
        "Generable": GenerableMacro.self,
        "Guide": GuideMacro.self,
        "Tool": ToolMacro.self,
        "Parameter": ParameterMacro.self,
      ],
      record: .never
    )
  )
  struct MacroSnapshotTests {

    // 1. @Generable struct — primitive properties.
    @Test func generableStructPrimitives() {
      assertMacro {
        """
        @Generable
        struct Person {
          @Guide(description: "Given name")
          var name: String
          var age: Int
        }
        """
      } expansion: {
        """
        struct Person {
          var name: String
          var age: Int

          private let _rawGeneratedContent: GeneratedContent

          nonisolated public init(name: String, age: Int) {
              self.name = name
                  self.age = age

              var properties: [String: GeneratedContent] = [:]
              properties["name"] = GeneratedContent(name)
                  properties["age"] = age.generatedContent

              self._rawGeneratedContent = GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["name", "age"]
                  )
              )
          }

          nonisolated public init(_ generatedContent: GeneratedContent) throws {
              struct MissingFieldKey: CodingKey {
                  var stringValue: String
                  var intValue: Int? {
                    nil
                  }
                  init(stringValue: String) {
                    self.stringValue = stringValue
                  }
                  init?(intValue: Int) {
                    nil
                  }
              }

              self._rawGeneratedContent = generatedContent

              guard case .structure(let properties, _) = generatedContent.kind else {
                  throw DecodingError.typeMismatch(
                      Person.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Expected structure for Person")
                  )
              }

              if let value = properties["name"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      String.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'name' was null")
                  )
              default:
                  self.name = try value.value(String.self)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "name"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'name'")
              )
              }
                      if let value = properties["age"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      Int.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'age' was null")
                  )
              default:
                  self.age = try value.value(Int.self)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "age"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'age'")
              )
              }
          }

          nonisolated public var generatedContent: GeneratedContent {
              var properties: [String: GeneratedContent] = [:]
              properties["name"] = GeneratedContent(name)
                      properties["age"] = age.generatedContent

              return GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["name", "age"]
                  )
              )
          }

          nonisolated public static var generationSchema: GenerationSchema {
              return GenerationSchema(
                  type: Self.self,
                  description: "Generated Person",
                  properties: [
                      GenerationSchema.Property(
                          name: "name",
                          description: "Given name",
                          type: String.self,
                          guides: []
                      ),
                      GenerationSchema.Property(
                          name: "age",
                          description: nil,
                          type: Int.self,
                          guides: []
                      )
                  ]
              )
          }

          public struct PartiallyGenerated: Identifiable, Sendable, ConvertibleFromGeneratedContent {
              public var id: GenerationID

              public let name: String?
                  public let age: Int?

              private let rawContent: GeneratedContent

              public init(_ generatedContent: GeneratedContent) throws {
                  self.id = generatedContent.id ?? GenerationID()
                  self.rawContent = generatedContent

                  if case .structure(let properties, _) = generatedContent.kind {
                      self.name = try? properties["name"]?.value(String.self)
                      self.age = try? properties["age"]?.value(Int.self)
                  } else {
                      self.name = nil
                              self.age = nil
                  }
              }

              public var generatedContent: GeneratedContent {
                  return rawContent
              }
          }

          nonisolated public func asPartiallyGenerated() -> PartiallyGenerated {
              return try! PartiallyGenerated(_rawGeneratedContent)
          }

          nonisolated public var instructionsRepresentation: Instructions {
              return Instructions(self.generatedContent.jsonString)
          }

          nonisolated public var promptRepresentation: Prompt {
              return Prompt(self.generatedContent.jsonString)
          }
        }
        """
      }
    }

    // 2. @Generable struct with a nested @Generable-typed field. Exercises
    // the schema builder's handling of user-defined Generable references.
    @Test func generableStructWithNestedGenerable() {
      assertMacro {
        """
        @Generable
        struct Address {
          var city: String
        }

        @Generable
        struct Contact {
          var name: String
          var address: Address
        }
        """
      } expansion: {
        """
        struct Address {
          var city: String

          private let _rawGeneratedContent: GeneratedContent

          nonisolated public init(city: String) {
              self.city = city

              var properties: [String: GeneratedContent] = [:]
              properties["city"] = GeneratedContent(city)

              self._rawGeneratedContent = GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["city"]
                  )
              )
          }

          nonisolated public init(_ generatedContent: GeneratedContent) throws {
              struct MissingFieldKey: CodingKey {
                  var stringValue: String
                  var intValue: Int? {
                    nil
                  }
                  init(stringValue: String) {
                    self.stringValue = stringValue
                  }
                  init?(intValue: Int) {
                    nil
                  }
              }

              self._rawGeneratedContent = generatedContent

              guard case .structure(let properties, _) = generatedContent.kind else {
                  throw DecodingError.typeMismatch(
                      Address.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Expected structure for Address")
                  )
              }

              if let value = properties["city"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      String.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'city' was null")
                  )
              default:
                  self.city = try value.value(String.self)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "city"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'city'")
              )
              }
          }

          nonisolated public var generatedContent: GeneratedContent {
              var properties: [String: GeneratedContent] = [:]
              properties["city"] = GeneratedContent(city)

              return GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["city"]
                  )
              )
          }

          nonisolated public static var generationSchema: GenerationSchema {
              return GenerationSchema(
                  type: Self.self,
                  description: "Generated Address",
                  properties: [
                      GenerationSchema.Property(
                          name: "city",
                          description: nil,
                          type: String.self,
                          guides: []
                      )
                  ]
              )
          }

          public struct PartiallyGenerated: Identifiable, Sendable, ConvertibleFromGeneratedContent {
              public var id: GenerationID

              public let city: String?

              private let rawContent: GeneratedContent

              public init(_ generatedContent: GeneratedContent) throws {
                  self.id = generatedContent.id ?? GenerationID()
                  self.rawContent = generatedContent

                  if case .structure(let properties, _) = generatedContent.kind {
                      self.city = try? properties["city"]?.value(String.self)
                  } else {
                      self.city = nil
                  }
              }

              public var generatedContent: GeneratedContent {
                  return rawContent
              }
          }

          nonisolated public func asPartiallyGenerated() -> PartiallyGenerated {
              return try! PartiallyGenerated(_rawGeneratedContent)
          }

          nonisolated public var instructionsRepresentation: Instructions {
              return Instructions(self.generatedContent.jsonString)
          }

          nonisolated public var promptRepresentation: Prompt {
              return Prompt(self.generatedContent.jsonString)
          }
        }
        struct Contact {
          var name: String
          var address: Address

          private let _rawGeneratedContent: GeneratedContent

          nonisolated public init(name: String, address: Address) {
              self.name = name
                  self.address = address

              var properties: [String: GeneratedContent] = [:]
              properties["name"] = GeneratedContent(name)
                  properties["address"] = address.generatedContent

              self._rawGeneratedContent = GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["name", "address"]
                  )
              )
          }

          nonisolated public init(_ generatedContent: GeneratedContent) throws {
              struct MissingFieldKey: CodingKey {
                  var stringValue: String
                  var intValue: Int? {
                    nil
                  }
                  init(stringValue: String) {
                    self.stringValue = stringValue
                  }
                  init?(intValue: Int) {
                    nil
                  }
              }

              self._rawGeneratedContent = generatedContent

              guard case .structure(let properties, _) = generatedContent.kind else {
                  throw DecodingError.typeMismatch(
                      Contact.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Expected structure for Contact")
                  )
              }

              if let value = properties["name"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      String.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'name' was null")
                  )
              default:
                  self.name = try value.value(String.self)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "name"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'name'")
              )
              }
                      if let value = properties["address"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      Address.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'address' was null")
                  )
              default:
                  self.address = try Address(value)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "address"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'address'")
              )
              }
          }

          nonisolated public var generatedContent: GeneratedContent {
              var properties: [String: GeneratedContent] = [:]
              properties["name"] = GeneratedContent(name)
                      properties["address"] = address.generatedContent

              return GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["name", "address"]
                  )
              )
          }

          nonisolated public static var generationSchema: GenerationSchema {
              return GenerationSchema(
                  type: Self.self,
                  description: "Generated Contact",
                  properties: [
                      GenerationSchema.Property(
                          name: "name",
                          description: nil,
                          type: String.self,
                          guides: []
                      ),
                      GenerationSchema.Property(
                          name: "address",
                          description: nil,
                          type: Address.self,
                          guides: []
                      )
                  ]
              )
          }

          public struct PartiallyGenerated: Identifiable, Sendable, ConvertibleFromGeneratedContent {
              public var id: GenerationID

              public let name: String?
                  public let address: Address.PartiallyGenerated?

              private let rawContent: GeneratedContent

              public init(_ generatedContent: GeneratedContent) throws {
                  self.id = generatedContent.id ?? GenerationID()
                  self.rawContent = generatedContent

                  if case .structure(let properties, _) = generatedContent.kind {
                      self.name = try? properties["name"]?.value(String.self)
                      if let value = properties["address"] {
              self.address = try? Address.PartiallyGenerated(value)
                      } else {
              self.address = nil
                      }
                  } else {
                      self.name = nil
                              self.address = nil
                  }
              }

              public var generatedContent: GeneratedContent {
                  return rawContent
              }
          }

          nonisolated public func asPartiallyGenerated() -> PartiallyGenerated {
              return try! PartiallyGenerated(_rawGeneratedContent)
          }

          nonisolated public var instructionsRepresentation: Instructions {
              return Instructions(self.generatedContent.jsonString)
          }

          nonisolated public var promptRepresentation: Prompt {
              return Prompt(self.generatedContent.jsonString)
          }
        }
        """
      }
    }

    // 3. @Generable enum with associated values — regression fixture for
    // commit af92a6b (correct init/generatedContent/schema synthesis).
    @Test func generableEnumAssociatedValues() {
      assertMacro {
        """
        @Generable
        enum SearchFilter {
          case keyword(String)
          case dateRange(start: Double, end: Double)
          case bounded(Int)
        }
        """
      } expansion: {
        #"""
        enum SearchFilter {
          case keyword(String)
          case dateRange(start: Double, end: Double)
          case bounded(Int)

          nonisolated public init(_ generatedContent: GeneratedContent) throws {
              do {
                  guard case .structure(let properties, _) = generatedContent.kind else {
                      throw DecodingError.typeMismatch(
                          SearchFilter.self,
                          DecodingError.Context(codingPath: [], debugDescription: "Expected structure for enum SearchFilter")
                      )
                  }

                  guard case .string(let caseValue) = properties["case"]?.kind else {
                      struct Key: CodingKey {
                          var stringValue: String
                          var intValue: Int? {
                            nil
                          }
                          init(stringValue: String) {
                            self.stringValue = stringValue
                          }
                          init?(intValue: Int) {
                            nil
                          }
                      }
                      throw DecodingError.keyNotFound(
                          Key(stringValue: "case"),
                          DecodingError.Context(codingPath: [], debugDescription: "Missing 'case' property in enum data for SearchFilter")
                      )
                  }

                  let valueContent = properties["value"]

                  switch caseValue {
                  case "keyword":
              if let valueContent = valueContent,
                 case .string(let stringValue) = valueContent.kind {
                  self = .keyword(stringValue)
              } else {
                  self = .keyword("")
              }
                          case "dateRange":
              if let valueContent = valueContent {
                  guard case .structure(let valueProperties, _) = valueContent.kind else {
                      throw DecodingError.typeMismatch(
                          [String: Any].self,
                          DecodingError.Context(codingPath: [], debugDescription: "Expected structure for enum case 'dateRange' associated values")
                      )
                  }
                  let start = try valueProperties["start"]?.value(Double.self) ?? 0.0
                              let end = try valueProperties["end"]?.value(Double.self) ?? 0.0
                  self = .dateRange(start: start, end: end)
              } else {
                  throw DecodingError.valueNotFound(
                      [String: Any].self,
                      DecodingError.Context(codingPath: [], debugDescription: "Missing value data for enum case 'dateRange' with associated values")
                  )
              }
                          case "bounded":
              if let valueContent = valueContent {
                  let intValue = try valueContent.value(Int.self)
                  self = .bounded(intValue)
              } else {
                  self = .bounded(0)
              }
                  default:
                      throw DecodingError.dataCorrupted(
                          DecodingError.Context(codingPath: [], debugDescription: "Invalid enum case '\(caseValue)' for SearchFilter. Valid cases: [keyword, dateRange, bounded]")
                      )
                  }
              } catch {
                  guard case .string(let value) = generatedContent.kind else {
                      throw error
                  }
                  let trimmedValue = value.trimmingCharacters(in: .whitespacesAndNewlines)
                  switch trimmedValue {

                  default:
                      throw DecodingError.dataCorrupted(
                          DecodingError.Context(codingPath: [], debugDescription: "Invalid enum case '\(trimmedValue)' for SearchFilter. Valid cases: [keyword, dateRange, bounded]")
                      )
                  }
              }
          }

          nonisolated public var generatedContent: GeneratedContent {
              switch self {
              case .keyword(let value):
              return GeneratedContent(properties: [
                  "case": GeneratedContent("keyword"),
                  "value": value.generatedContent
              ])
                      case .dateRange(let start, let end):
              return GeneratedContent(properties: [
                  "case": GeneratedContent("dateRange"),
                  "value": GeneratedContent(properties: [
                      "start": start.generatedContent,
                                  "end": end.generatedContent
                  ])
              ])
                      case .bounded(let value):
              return GeneratedContent(properties: [
                  "case": GeneratedContent("bounded"),
                  "value": value.generatedContent
              ])
              }
          }

          nonisolated public static var generationSchema: GenerationSchema {
              let caseSchema = DynamicGenerationSchema(
                  name: "SearchFilter_Case",
                  anyOf: ["keyword", "dateRange", "bounded"]
              )
              let valueSchema = DynamicGenerationSchema(
                  name: "SearchFilter_Value",
                  anyOf: [DynamicGenerationSchema(type: String.self), DynamicGenerationSchema(name: "SearchFilter_dateRange_Payload", properties: [DynamicGenerationSchema.Property(name: "start", schema: DynamicGenerationSchema(type: Double.self)), DynamicGenerationSchema.Property(name: "end", schema: DynamicGenerationSchema(type: Double.self))]), DynamicGenerationSchema(type: Int.self)]
              )
              let root = DynamicGenerationSchema(
                  name: String(reflecting: Self.self),
                  description: "Generated SearchFilter",
                  properties: [
                      DynamicGenerationSchema.Property(
                          name: "case",
                          description: "Enum case identifier",
                          schema: caseSchema
                      ),
                      DynamicGenerationSchema.Property(
                          name: "value",
                          description: "Associated value data",
                          schema: valueSchema
                      )
                  ]
              )
              do {
                  return try GenerationSchema(root: root, dependencies: [])
              } catch {
                  fatalError("Failed to build generationSchema for SearchFilter: \(error)")
              }
          }

          nonisolated public func asPartiallyGenerated() -> SearchFilter {
              return self
          }

          nonisolated public var instructionsRepresentation: Instructions {
              return Instructions(self.generatedContent.jsonString)
          }

          nonisolated public var promptRepresentation: Prompt {
              return Prompt(self.generatedContent.jsonString)
          }
        }
        """#
      }
    }

    // 4. @Guide(Regex) — pattern literal must flow into schema (91e2948).
    @Test func generableGuideRegexPattern() {
      assertMacro {
        """
        @Generable
        struct Tagged {
          @Guide(/[A-Za-z]+/)
          var name: String

          @Guide(description: "hex color", /#[0-9A-Fa-f]{6}/)
          var color: String
        }
        """
      } expansion: {
        """
        struct Tagged {
          var name: String
          var color: String

          private let _rawGeneratedContent: GeneratedContent

          nonisolated public init(name: String, color: String) {
              self.name = name
                  self.color = color

              var properties: [String: GeneratedContent] = [:]
              properties["name"] = GeneratedContent(name)
                  properties["color"] = GeneratedContent(color)

              self._rawGeneratedContent = GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["name", "color"]
                  )
              )
          }

          nonisolated public init(_ generatedContent: GeneratedContent) throws {
              struct MissingFieldKey: CodingKey {
                  var stringValue: String
                  var intValue: Int? {
                    nil
                  }
                  init(stringValue: String) {
                    self.stringValue = stringValue
                  }
                  init?(intValue: Int) {
                    nil
                  }
              }

              self._rawGeneratedContent = generatedContent

              guard case .structure(let properties, _) = generatedContent.kind else {
                  throw DecodingError.typeMismatch(
                      Tagged.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Expected structure for Tagged")
                  )
              }

              if let value = properties["name"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      String.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'name' was null")
                  )
              default:
                  self.name = try value.value(String.self)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "name"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'name'")
              )
              }
                      if let value = properties["color"] {
              switch value.kind {
              case .null:
                  throw DecodingError.valueNotFound(
                      String.self,
                      DecodingError.Context(codingPath: [], debugDescription: "Required property 'color' was null")
                  )
              default:
                  self.color = try value.value(String.self)
              }
              } else {
              throw DecodingError.keyNotFound(
                  MissingFieldKey(stringValue: "color"),
                  DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'color'")
              )
              }
          }

          nonisolated public var generatedContent: GeneratedContent {
              var properties: [String: GeneratedContent] = [:]
              properties["name"] = GeneratedContent(name)
                      properties["color"] = GeneratedContent(color)

              return GeneratedContent(
                  kind: .structure(
                      properties: properties,
                      orderedKeys: ["name", "color"]
                  )
              )
          }

          nonisolated public static var generationSchema: GenerationSchema {
              return GenerationSchema(
                  type: Self.self,
                  description: "Generated Tagged",
                  properties: [
                      GenerationSchema.Property(
                          name: "name",
                          description: nil,
                          type: String.self,
                          guides: [.pattern("[A-Za-z]+")]
                      ),
                      GenerationSchema.Property(
                          name: "color",
                          description: "hex color",
                          type: String.self,
                          guides: [.pattern("#[0-9A-Fa-f]{6}")]
                      )
                  ]
              )
          }

          public struct PartiallyGenerated: Identifiable, Sendable, ConvertibleFromGeneratedContent {
              public var id: GenerationID

              public let name: String?
                  public let color: String?

              private let rawContent: GeneratedContent

              public init(_ generatedContent: GeneratedContent) throws {
                  self.id = generatedContent.id ?? GenerationID()
                  self.rawContent = generatedContent

                  if case .structure(let properties, _) = generatedContent.kind {
                      self.name = try? properties["name"]?.value(String.self)
                      self.color = try? properties["color"]?.value(String.self)
                  } else {
                      self.name = nil
                              self.color = nil
                  }
              }

              public var generatedContent: GeneratedContent {
                  return rawContent
              }
          }

          nonisolated public func asPartiallyGenerated() -> PartiallyGenerated {
              return try! PartiallyGenerated(_rawGeneratedContent)
          }

          nonisolated public var instructionsRepresentation: Instructions {
              return Instructions(self.generatedContent.jsonString)
          }

          nonisolated public var promptRepresentation: Prompt {
              return Prompt(self.generatedContent.jsonString)
          }
        }
        """
      }
    }

    // 5. @Tool simple — top-level tool with execute + nested Arguments.
    @Test func toolSimple() {
      assertMacro {
        """
        @Tool("Returns the current date/time.")
        struct GetCurrentDateTool {
          @Generable
          struct Arguments {
            @Guide(description: "IANA timezone identifier")
            var timezone: String
          }

          func execute(_ arguments: Arguments) async throws -> String {
            "2026-04-22T00:00:00 (\\(arguments.timezone))"
          }
        }
        """
      } expansion: {
        #"""
        struct GetCurrentDateTool {
          struct Arguments {
            var timezone: String

            private let _rawGeneratedContent: GeneratedContent

            nonisolated public init(timezone: String) {
                self.timezone = timezone

                var properties: [String: GeneratedContent] = [:]
                properties["timezone"] = GeneratedContent(timezone)

                self._rawGeneratedContent = GeneratedContent(
                    kind: .structure(
                        properties: properties,
                        orderedKeys: ["timezone"]
                    )
                )
            }

            nonisolated public init(_ generatedContent: GeneratedContent) throws {
                struct MissingFieldKey: CodingKey {
                    var stringValue: String
                    var intValue: Int? {
                      nil
                    }
                    init(stringValue: String) {
                      self.stringValue = stringValue
                    }
                    init?(intValue: Int) {
                      nil
                    }
                }

                self._rawGeneratedContent = generatedContent

                guard case .structure(let properties, _) = generatedContent.kind else {
                    throw DecodingError.typeMismatch(
                        Arguments.self,
                        DecodingError.Context(codingPath: [], debugDescription: "Expected structure for Arguments")
                    )
                }

                if let value = properties["timezone"] {
                switch value.kind {
                case .null:
                    throw DecodingError.valueNotFound(
                        String.self,
                        DecodingError.Context(codingPath: [], debugDescription: "Required property 'timezone' was null")
                    )
                default:
                    self.timezone = try value.value(String.self)
                }
                } else {
                throw DecodingError.keyNotFound(
                    MissingFieldKey(stringValue: "timezone"),
                    DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'timezone'")
                )
                }
            }

            nonisolated public var generatedContent: GeneratedContent {
                var properties: [String: GeneratedContent] = [:]
                properties["timezone"] = GeneratedContent(timezone)

                return GeneratedContent(
                    kind: .structure(
                        properties: properties,
                        orderedKeys: ["timezone"]
                    )
                )
            }

            nonisolated public static var generationSchema: GenerationSchema {
                return GenerationSchema(
                    type: Self.self,
                    description: "Generated Arguments",
                    properties: [
                        GenerationSchema.Property(
                            name: "timezone",
                            description: "IANA timezone identifier",
                            type: String.self,
                            guides: []
                        )
                    ]
                )
            }

            public struct PartiallyGenerated: Identifiable, Sendable, ConvertibleFromGeneratedContent {
                public var id: GenerationID

                public let timezone: String?

                private let rawContent: GeneratedContent

                public init(_ generatedContent: GeneratedContent) throws {
                    self.id = generatedContent.id ?? GenerationID()
                    self.rawContent = generatedContent

                    if case .structure(let properties, _) = generatedContent.kind {
                        self.timezone = try? properties["timezone"]?.value(String.self)
                    } else {
                        self.timezone = nil
                    }
                }

                public var generatedContent: GeneratedContent {
                    return rawContent
                }
            }

            nonisolated public func asPartiallyGenerated() -> PartiallyGenerated {
                return try! PartiallyGenerated(_rawGeneratedContent)
            }

            nonisolated public var instructionsRepresentation: Instructions {
                return Instructions(self.generatedContent.jsonString)
            }

            nonisolated public var promptRepresentation: Prompt {
                return Prompt(self.generatedContent.jsonString)
            }
          }

          func execute(_ arguments: Arguments) async throws -> String {
            "2026-04-22T00:00:00 (\(arguments.timezone))"
          }

          public var name: String {
            Self.schema.name
          }

          public var description: String {
            Self.schema.description
          }

          public var parameters: SwiftAIHub.GenerationSchema {
            Self.schema.generationSchema
          }

          public static let schema: SwiftAIHub.ToolSchema = SwiftAIHub.ToolSchema(
              name: "getCurrentDate",
              description: "Returns the current date/time.",
              generationSchema: Arguments.generationSchema
          )

          public init() {
          }

          public typealias Output = String

          public func call(arguments: Arguments) async throws -> Output {
              try await self.execute(arguments)
          }
        }

        extension GetCurrentDateTool: SwiftAIHub.Tool, Swift.Sendable {
        }
        """#
      }
    }

    // 6. @Tool + @Parameter — Arguments uses the @Parameter marker.
    @Test func toolWithParameter() {
      assertMacro {
        """
        @Tool("Echoes the given message a number of times.")
        struct EchoTool {
          @Generable
          struct Arguments {
            @Parameter("Message to echo")
            var message: String

            @Parameter("Repeat count")
            var count: Int
          }

          func execute(_ arguments: Arguments) async throws -> String {
            String(repeating: arguments.message, count: arguments.count)
          }
        }
        """
      } expansion: {
        """
        struct EchoTool {
          struct Arguments {
            var message: String
            var count: Int

            private let _rawGeneratedContent: GeneratedContent

            nonisolated public init(message: String, count: Int) {
                self.message = message
                    self.count = count

                var properties: [String: GeneratedContent] = [:]
                properties["message"] = GeneratedContent(message)
                    properties["count"] = count.generatedContent

                self._rawGeneratedContent = GeneratedContent(
                    kind: .structure(
                        properties: properties,
                        orderedKeys: ["message", "count"]
                    )
                )
            }

            nonisolated public init(_ generatedContent: GeneratedContent) throws {
                struct MissingFieldKey: CodingKey {
                    var stringValue: String
                    var intValue: Int? {
                      nil
                    }
                    init(stringValue: String) {
                      self.stringValue = stringValue
                    }
                    init?(intValue: Int) {
                      nil
                    }
                }

                self._rawGeneratedContent = generatedContent

                guard case .structure(let properties, _) = generatedContent.kind else {
                    throw DecodingError.typeMismatch(
                        Arguments.self,
                        DecodingError.Context(codingPath: [], debugDescription: "Expected structure for Arguments")
                    )
                }

                if let value = properties["message"] {
                switch value.kind {
                case .null:
                    throw DecodingError.valueNotFound(
                        String.self,
                        DecodingError.Context(codingPath: [], debugDescription: "Required property 'message' was null")
                    )
                default:
                    self.message = try value.value(String.self)
                }
                } else {
                throw DecodingError.keyNotFound(
                    MissingFieldKey(stringValue: "message"),
                    DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'message'")
                )
                }
                        if let value = properties["count"] {
                switch value.kind {
                case .null:
                    throw DecodingError.valueNotFound(
                        Int.self,
                        DecodingError.Context(codingPath: [], debugDescription: "Required property 'count' was null")
                    )
                default:
                    self.count = try value.value(Int.self)
                }
                } else {
                throw DecodingError.keyNotFound(
                    MissingFieldKey(stringValue: "count"),
                    DecodingError.Context(codingPath: [], debugDescription: "Missing required property 'count'")
                )
                }
            }

            nonisolated public var generatedContent: GeneratedContent {
                var properties: [String: GeneratedContent] = [:]
                properties["message"] = GeneratedContent(message)
                        properties["count"] = count.generatedContent

                return GeneratedContent(
                    kind: .structure(
                        properties: properties,
                        orderedKeys: ["message", "count"]
                    )
                )
            }

            nonisolated public static var generationSchema: GenerationSchema {
                return GenerationSchema(
                    type: Self.self,
                    description: "Generated Arguments",
                    properties: [
                        GenerationSchema.Property(
                            name: "message",
                            description: "Message to echo",
                            type: String.self,
                            guides: []
                        ),
                        GenerationSchema.Property(
                            name: "count",
                            description: "Repeat count",
                            type: Int.self,
                            guides: []
                        )
                    ]
                )
            }

            public struct PartiallyGenerated: Identifiable, Sendable, ConvertibleFromGeneratedContent {
                public var id: GenerationID

                public let message: String?
                    public let count: Int?

                private let rawContent: GeneratedContent

                public init(_ generatedContent: GeneratedContent) throws {
                    self.id = generatedContent.id ?? GenerationID()
                    self.rawContent = generatedContent

                    if case .structure(let properties, _) = generatedContent.kind {
                        self.message = try? properties["message"]?.value(String.self)
                        self.count = try? properties["count"]?.value(Int.self)
                    } else {
                        self.message = nil
                                self.count = nil
                    }
                }

                public var generatedContent: GeneratedContent {
                    return rawContent
                }
            }

            nonisolated public func asPartiallyGenerated() -> PartiallyGenerated {
                return try! PartiallyGenerated(_rawGeneratedContent)
            }

            nonisolated public var instructionsRepresentation: Instructions {
                return Instructions(self.generatedContent.jsonString)
            }

            nonisolated public var promptRepresentation: Prompt {
                return Prompt(self.generatedContent.jsonString)
            }
          }

          func execute(_ arguments: Arguments) async throws -> String {
            String(repeating: arguments.message, count: arguments.count)
          }

          public var name: String {
            Self.schema.name
          }

          public var description: String {
            Self.schema.description
          }

          public var parameters: SwiftAIHub.GenerationSchema {
            Self.schema.generationSchema
          }

          public static let schema: SwiftAIHub.ToolSchema = SwiftAIHub.ToolSchema(
              name: "echo",
              description: "Echoes the given message a number of times.",
              generationSchema: Arguments.generationSchema
          )

          public init() {
          }

          public typealias Output = String

          public func call(arguments: Arguments) async throws -> Output {
              try await self.execute(arguments)
          }
        }

        extension EchoTool: SwiftAIHub.Tool, Swift.Sendable {
        }
        """
      }
    }
  }
#endif
