// swift-ai-hub — Apache-2.0
//
// Typed error surface for HuggingFaceLanguageModel. Kept in a dedicated file
// so the main provider file stays focused on request wiring.

import Foundation

/// Provider-typed errors thrown by ``HuggingFaceLanguageModel``.
public enum HuggingFaceLanguageModelError: LocalizedError, Sendable {
  /// HTTP 401 Unauthorized — missing, invalid, or revoked HF token.
  case unauthorized(message: String)

  /// HTTP 403 Forbidden — authenticated but the token lacks access to the
  /// target model (for example a gated model without an accepted license).
  case forbidden(message: String)

  /// HTTP 429 Too Many Requests. Rate-limit headers, when present, are
  /// parsed into a ``RateLimitInfo`` for the caller.
  case rateLimited(message: String, rateLimit: RateLimitInfo?)

  /// HTTP 503 with an `estimated_time` body indicating the model is still
  /// loading on HF's inference infrastructure.
  case modelDownloading(estimatedTime: TimeInterval)

  /// Other 5xx responses without the cold-start marker.
  case serverError(statusCode: Int, message: String)

  /// Any other non-2xx HTTP response.
  case httpError(statusCode: Int, message: String)

  /// Model id validation failed (empty string).
  case invalidModelID

  /// The server returned 200 but no usable completion was produced.
  case noResponseGenerated

  /// The URL session returned a non-HTTP response.
  case invalidResponse

  /// A decoding failure after the transport succeeded.
  case decodingFailed(detail: String)

  public var errorDescription: String? {
    switch self {
    case .unauthorized(let m): return "HuggingFace authentication failed: \(m)"
    case .forbidden(let m): return "HuggingFace access denied: \(m)"
    case .rateLimited(let m, _): return "HuggingFace rate limited: \(m)"
    case .modelDownloading(let t):
      return "HuggingFace model is still loading (estimated \(t)s)"
    case .serverError(let code, let m): return "HuggingFace server error (\(code)): \(m)"
    case .httpError(let code, let m): return "HuggingFace HTTP error (\(code)): \(m)"
    case .invalidModelID: return "HuggingFace model id must not be empty"
    case .noResponseGenerated: return "No response was generated by the model"
    case .invalidResponse: return "Invalid HTTP response from HuggingFace"
    case .decodingFailed(let d): return "Failed to decode HuggingFace response: \(d)"
    }
  }
}

extension HuggingFaceLanguageModelError: LanguageModelError {
  public var httpStatus: Int? {
    switch self {
    case .unauthorized: return 401
    case .forbidden: return 403
    case .rateLimited: return 429
    case .modelDownloading: return 503
    case .serverError(let code, _): return code
    case .httpError(let code, _): return code
    case .invalidModelID, .noResponseGenerated, .invalidResponse, .decodingFailed:
      return nil
    }
  }

  public var providerMessage: String {
    redactSensitiveHeaders(errorDescription ?? String(describing: self))
  }

  public var isRetryable: Bool {
    switch self {
    case .rateLimited, .modelDownloading, .serverError:
      return true
    case .httpError(let code, _):
      return isRetryableHTTPStatus(code)
    case .unauthorized, .forbidden, .invalidModelID, .noResponseGenerated,
      .invalidResponse, .decodingFailed:
      return false
    }
  }

  public var description: String { providerMessage }
}
